#!/usr/bin/env bash
# The MIT License (MIT)
#
# Copyright © 2023-2025 Stephen G. Tuggy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

echo "--------------------------"
echo "--- build | 2025-01-10 ---"
echo "--------------------------"

#----------------------------------
# validate parameters
#----------------------------------

ROOT_DIR=$(pwd)
echo "ROOT_DIR: ${ROOT_DIR}"
BUILD_DIR="${ROOT_DIR}/build"
echo "BUILD_DIR: ${BUILD_DIR}"
BIN_DIR="${ROOT_DIR}/bin"
COMMAND=""

# -p creates if the target doesn't exist, noop otherwise
mkdir -pv "${BUILD_DIR}" && cd "${BUILD_DIR}"

cmake $@ "${ROOT_DIR}"

MAX_THREADS_TO_BUILD_WITH=8
NUM_THREADS_TO_BUILD_WITH=$(getconf _NPROCESSORS_ONLN)
if [ ${NUM_THREADS_TO_BUILD_WITH} -gt ${MAX_THREADS_TO_BUILD_WITH} ]
then
    NUM_THREADS_TO_BUILD_WITH=${MAX_THREADS_TO_BUILD_WITH}
fi

VERBOSE=1 cmake --build "${BUILD_DIR}" -j ${NUM_THREADS_TO_BUILD_WITH}
