#!/usr/bin/env bash
# The MIT License (MIT)
#
# Copyright © 2023-2026 Stephen G. Tuggy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

echo "----------------------------"
echo "--- cibuild | 2026-04-29 ---"
echo "----------------------------"

#----------------------------------
# validate parameters
#----------------------------------

while [ $# -gt 0 ]; do
  case "$1" in
    --preset_name=*)
      preset_name="${1#*=}"
      ;;
    --preset-name=*)
      preset_name="${1#*=}"
      ;;
    --build_type=*)
      build_type="${1#*=}"
      ;;
    --build-type=*)
      build_type="${1#*=}"
      ;;
    *)
      printf "***************************\n"
      printf "* Error: Invalid argument.*\n"
      printf "***************************\n"
      exit 1
      ;;
  esac
  shift
done

if [ "${COMPILER}" == "gcc" ]
then
  export CC=gcc
  export CXX=g++
elif [ "${COMPILER}" == "clang" ]
then
  export CC=clang
  export CXX=clang++
fi

if [ $IS_RELEASE -eq 1 ]
then
  export INSTALL_GTEST=0
  export USE_GTEST=0
fi

if [ -z "$from" ] && [ -n "$FROM" ]
then
  from="${FROM}"
fi

if [ -z "$preset_name" ] && [ -n "$PRESET_NAME" ]
then
  preset_name="${PRESET_NAME}"
fi

platform="$(uname | tr '[:upper:]' '[:lower:]')"

case "$platform" in
  "linux"|"linux-gnu")
    DOCKER_IMG_NAME="local_building-boost-log-python-poc:$(echo "${from}" | sed 's/:/_/' | sed 's/\//_/')"
    DOCKER_CONTAINER_NAME="building-boost-log-python-poc_$(echo "${from}" | sed 's/:/_/' | sed 's/\//_/')"
    PRESET_NAME="${preset_name}"
    echo "Building docker image for ${from}"
    docker build --build-arg from="${from}" -t "$DOCKER_IMG_NAME" .
    echo "Running docker image for ${from} / ${COMPILER}"
    docker run --env CC="$CC" --env CXX="$CXX" --env IS_RELEASE="$IS_RELEASE" --env TAG_NAME="$TAG_NAME" --env GITHUB_SHA="$GITHUB_SHA" --env SHORT_SHA="$SHORT_SHA" --env PRESET_NAME="$PRESET_NAME" --name "$DOCKER_CONTAINER_NAME" "$DOCKER_IMG_NAME"
    docker rm "$DOCKER_CONTAINER_NAME"
    ;;
  "darwin")
    script/docker-entrypoint.sh --preset_name="${preset_name}"
    ;;
  *)
    echo "Sorry, unrecognized or unsupported operating system"
    exit 2
    ;;
esac

echo "cibuild Done!"
