# The MIT License (MIT)
#
# Copyright © 2025-2026 Stephen G. Tuggy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

name: MacOS-CI
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS-15
            build-type: RelWithDebInfo
            preset-name: macos-pie-enabled-RelWithDebInfo
          - os: macOS-26
            build-type: Debug
            preset-name: macos-pie-enabled-debug

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
          submodules: false

      - name: Install dependencies using homebrew
        run: ./script/bootstrap 1

      - name: Install CMake
        uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2

      - name: Build the code
        working-directory: ${{ github.workspace }}
        env:
          PYTHONHOME: ""
          PYTHONPATH: ""
        run: ./script/build --preset_name=${{ matrix.preset-name }}

      - name: Test the code
        working-directory: ${{ github.workspace }}
        env:
          PYTHONUNBUFFERED: 1
        run: ./script/test --preset_name=${{ matrix.preset-name }} --build_type=${{ matrix.build-type }}
